export const APP_CONSTANTS = {
  BCRYPT_SALT_ROUNDS: 12,
  MAX_EMAILS_PER_DAY: 50,
  MAX_FAILED_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
  VERIFICATION_TOKEN_EXPIRES_HOURS: 24,
  RESET_TOKEN_EXPIRES_HOURS: 1,
  SCRAPER_INTERVAL_MINUTES: 120,
  RATE_LIMIT_AUTH: { windowMs: 60_000, max: 10 },
  RATE_LIMIT_API: { windowMs: 60_000, max: 100 },
  PAGINATION_DEFAULT_PAGE: 1,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,
} as const;
