import { PrismaClient } from '../generated/prisma';
import { faker } from '@faker-js/faker';

const prisma = new PrismaClient();
const HR_EMAIL = process.env.TEST_HR_EMAIL || 'test@hrdata.test';

const count = parseInt(process.argv[2] || '1', 10);

async function main() {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

  const jobs = [
    {
      title: 'مطور باك إند (Node.js)',
      companyName: 'شركة STC',
      source: 'لينكد إن',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description:
        'نبحث عن مطور باك إند متمكن من Node.js للانضمام إلى فريقنا التقني. يُشترط خبرة لا تقل عن ٣ سنوات في تطوير APIs وإدارة قواعد البيانات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/شركة-stc-1',
      language: 'ar',
      postedAt: '2026-04-01T09:00:00.000Z',
      expiresAt: '2026-05-01T23:59:59.000Z',
    },
    {
      title: 'مهندس واجهات أمامية (React)',
      companyName: 'أرامكو السعودية',
      source: 'وظف',
      location: 'JEDDAH',
      category: 'تطوير الواجهات الأمامية',
      description:
        'مطلوب مهندس React لتطوير واجهات مستخدم احترافية وسريعة الأداء ضمن فريق منتج متكامل.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/أرامكو-السعودية-2',
      language: 'ar',
      postedAt: '2026-04-02T09:00:00.000Z',
      expiresAt: '2026-05-02T23:59:59.000Z',
    },
    {
      title: 'مهندس DevOps',
      companyName: 'نيوم',
      source: 'جلاس دور',
      location: 'DAMMAM',
      category: 'البنية التحتية والعمليات',
      description:
        'فرصة للانضمام إلى فريق البنية التحتية. ستكون مسؤولاً عن إدارة خطوط CI/CD والنشر السحابي.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/نيوم-3',
      language: 'ar',
      postedAt: '2026-04-03T09:00:00.000Z',
      expiresAt: '2026-05-03T23:59:59.000Z',
    },
    {
      title: 'عالم بيانات',
      companyName: 'موبايلي',
      source: 'بيت',
      location: 'KHOBAR',
      category: 'علم البيانات',
      description:
        'فرصة مميزة لعالم بيانات متخصص في تحليل السلوك والنمذجة الإحصائية. خبرة في Python وSQL مطلوبة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/موبايلي-4',
      language: 'ar',
      postedAt: '2026-04-04T09:00:00.000Z',
      expiresAt: '2026-05-04T23:59:59.000Z',
    },
    {
      title: 'مصمم واجهات المستخدم (UI/UX)',
      companyName: 'stc pay',
      source: 'إنديد',
      location: 'MECCA',
      category: 'تصميم تجربة المستخدم',
      description: 'نبحث عن مصمم UI/UX مبدع لتصميم تجارب مستخدم سلسة لتطبيقات الويب والجوال.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/stc-pay-5',
      language: 'ar',
      postedAt: '2026-04-05T09:00:00.000Z',
      expiresAt: '2026-05-05T23:59:59.000Z',
    },
    {
      title: 'مطور تطبيقات جوال (Flutter)',
      companyName: 'نون',
      source: 'ناوكري غلف',
      location: 'MEDINA',
      category: 'تطوير تطبيقات الجوال',
      description: 'مطلوب مطور Flutter لبناء تطبيقات جوال عالية الأداء على منصتي iOS وAndroid.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/نون-6',
      language: 'ar',
      postedAt: '2026-04-06T09:00:00.000Z',
      expiresAt: '2026-05-06T23:59:59.000Z',
    },
    {
      title: 'محلل أمن معلومات',
      companyName: 'جرير',
      source: 'لينكد إن',
      location: 'TABUK',
      category: 'الأمن السيبراني',
      description:
        'نبحث عن محلل أمن معلومات لحماية البنية التحتية الرقمية من التهديدات السيبرانية المتطورة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/جرير-7',
      language: 'ar',
      postedAt: '2026-04-07T09:00:00.000Z',
      expiresAt: '2026-05-07T23:59:59.000Z',
    },
    {
      title: 'مهندس ضمان الجودة (Automation)',
      companyName: 'بنك الراجحي',
      source: 'وظف',
      location: 'RIYADH',
      category: 'ضمان الجودة',
      description:
        'مطلوب مهندس أتمتة اختبارات للعمل على تطبيقات حساسة. خبرة في Selenium أو Cypress مطلوبة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/بنك-الراجحي-8',
      language: 'ar',
      postedAt: '2026-04-08T09:00:00.000Z',
      expiresAt: '2026-05-08T23:59:59.000Z',
    },
    {
      title: 'مدير منتج تقني',
      companyName: 'سابك',
      source: 'جلاس دور',
      location: 'JEDDAH',
      category: 'إدارة المنتجات',
      description: 'فرصة لإدارة دورة حياة منتج تقني كاملة ضمن فريق متعدد التخصصات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/سابك-9',
      language: 'ar',
      postedAt: '2026-04-09T09:00:00.000Z',
      expiresAt: '2026-05-09T23:59:59.000Z',
    },
    {
      title: 'مطور فول ستاك',
      companyName: 'إلم',
      source: 'بيت',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'نبحث عن مطور Full Stack متمكن من React وNode.js للعمل على منصات رقمية متقدمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/إلم-10',
      language: 'ar',
      postedAt: '2026-04-10T09:00:00.000Z',
      expiresAt: '2026-05-10T23:59:59.000Z',
    },
    {
      title: 'مهندس سحابي (AWS)',
      companyName: 'يونيفونيك',
      source: 'إنديد',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'مطلوب مهندس AWS لتصميم وإدارة بنية تحتية سحابية موثوقة وقابلة للتوسع.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/يونيفونيك-11',
      language: 'ar',
      postedAt: '2026-04-11T09:00:00.000Z',
      expiresAt: '2026-05-11T23:59:59.000Z',
    },
    {
      title: 'مهندس تعلم آلي',
      companyName: 'فودكس',
      source: 'ناوكري غلف',
      location: 'MECCA',
      category: 'علم البيانات',
      description:
        'فرصة للعمل في تطوير نماذج تعلم آلي لتحسين تجربة المستخدم وتحليل البيانات الضخمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/فودكس-12',
      language: 'ar',
      postedAt: '2026-04-12T09:00:00.000Z',
      expiresAt: '2026-05-12T23:59:59.000Z',
    },
    {
      title: 'مطور Node.js',
      companyName: 'تمارا',
      source: 'لينكد إن',
      location: 'MEDINA',
      category: 'تطوير الواجهة الخلفية',
      description: 'نبحث عن مطور Node.js متمكن للعمل على خدمات الويب وتكاملات APIs.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/تمارا-13',
      language: 'ar',
      postedAt: '2026-04-13T09:00:00.000Z',
      expiresAt: '2026-05-13T23:59:59.000Z',
    },
    {
      title: 'مهندس TypeScript',
      companyName: 'تابي',
      source: 'وظف',
      location: 'TABUK',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مهندس TypeScript متمكن لتطوير حلول تقنية حديثة ضمن فريق متخصص.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/تابي-14',
      language: 'ar',
      postedAt: '2026-04-14T09:00:00.000Z',
      expiresAt: '2026-05-14T23:59:59.000Z',
    },
    {
      title: 'مدير قواعد بيانات',
      companyName: 'جيديا',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'علم البيانات',
      description:
        'مطلوب مدير قواعد بيانات متخصص في PostgreSQL لإدارة قواعد بيانات الأنظمة الحساسة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/جيديا-15',
      language: 'ar',
      postedAt: '2026-04-15T09:00:00.000Z',
      expiresAt: '2026-05-15T23:59:59.000Z',
    },
    {
      title: 'مهندس معماريات الأنظمة',
      companyName: 'ليان تكنولوجيز',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'هندسة البرمجيات',
      description: 'فرصة لتصميم معماريات أنظمة رقمية متقدمة تخدم ملايين المستخدمين.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/ليان-تكنولوجيز-16',
      language: 'ar',
      postedAt: '2026-04-16T09:00:00.000Z',
      expiresAt: '2026-05-16T23:59:59.000Z',
    },
    {
      title: 'مطور واجهات برمجية (API)',
      companyName: 'موزن',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'الأمن السيبراني',
      description: 'نوفر فرصة لمطور APIs في مجال الذكاء الاصطناعي والحلول التقنية المتقدمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/موزن-17',
      language: 'ar',
      postedAt: '2026-04-17T09:00:00.000Z',
      expiresAt: '2026-05-17T23:59:59.000Z',
    },
    {
      title: 'سكرام ماستر',
      companyName: 'إيجادة',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'إدارة المنتجات',
      description: 'مطلوب Scrum Master معتمد لقيادة فرق تطوير البرمجيات وفق منهجية أجايل.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/إيجادة-18',
      language: 'ar',
      postedAt: '2026-04-18T09:00:00.000Z',
      expiresAt: '2026-05-18T23:59:59.000Z',
    },
    {
      title: 'قائد تقني (Tech Lead)',
      companyName: 'سلة',
      source: 'لينكد إن',
      location: 'MECCA',
      category: 'تطوير تطبيقات الجوال',
      description: 'نبحث عن قائد تقني لقيادة فريق هندسة وتطوير منصات إلكترونية متكاملة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/سلة-19',
      language: 'ar',
      postedAt: '2026-04-19T09:00:00.000Z',
      expiresAt: '2026-05-19T23:59:59.000Z',
    },
    {
      title: 'مهندس برمجيات',
      companyName: 'زد',
      source: 'وظف',
      location: 'MEDINA',
      category: 'ضمان الجودة',
      description: 'انضم كمهندس برمجيات وساهم في بناء منصة تخدم آلاف المستخدمين يومياً.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/زد-20',
      language: 'ar',
      postedAt: '2026-04-20T09:00:00.000Z',
      expiresAt: '2026-05-20T23:59:59.000Z',
    },
    {
      title: 'مطور React Native',
      companyName: 'حسوب',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'تطوير تطبيقات الجوال',
      description: 'مطلوب مطور React Native لبناء تطبيقات جوال متعددة المنصات بأداء عالٍ.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/حسوب-21',
      language: 'ar',
      postedAt: '2026-04-21T09:00:00.000Z',
      expiresAt: '2026-05-21T23:59:59.000Z',
    },
    {
      title: 'مهندس أمن تطبيقات',
      companyName: 'كيان',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'الأمن السيبراني',
      description: 'فرصة للعمل في مجال أمن التطبيقات واختبار الاختراق لحماية المنصات الرقمية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/كيان-22',
      language: 'ar',
      postedAt: '2026-04-22T09:00:00.000Z',
      expiresAt: '2026-05-22T23:59:59.000Z',
    },
    {
      title: 'محلل بيانات (Power BI)',
      companyName: 'بيانات',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'علم البيانات',
      description:
        'مطلوب محلل بيانات متمكن من Power BI وExcel المتقدم لإنشاء تقارير تحليلية دقيقة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/بيانات-23',
      language: 'ar',
      postedAt: '2026-04-23T09:00:00.000Z',
      expiresAt: '2026-05-23T23:59:59.000Z',
    },
    {
      title: 'مطور Python',
      companyName: 'فاتورة',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'هندسة البرمجيات',
      description: 'نبحث عن مطور Python متمكن للعمل على أنظمة معالجة البيانات والأتمتة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/فاتورة-24',
      language: 'ar',
      postedAt: '2026-04-24T09:00:00.000Z',
      expiresAt: '2026-05-24T23:59:59.000Z',
    },
    {
      title: 'مصمم تجربة المستخدم (UX Research)',
      companyName: 'ثروة',
      source: 'لينكد إن',
      location: 'MECCA',
      category: 'تصميم تجربة المستخدم',
      description: 'مطلوب باحث UX لإجراء دراسات المستخدم وتحسين تجربة المنتجات الرقمية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/ثروة-25',
      language: 'ar',
      postedAt: '2026-04-25T09:00:00.000Z',
      expiresAt: '2026-05-25T23:59:59.000Z',
    },
    {
      title: 'مهندس Kubernetes',
      companyName: 'نافذة',
      source: 'وظف',
      location: 'TABUK',
      category: 'البنية التحتية والعمليات',
      description: 'فرصة للعمل مع Kubernetes وDocker في بيئة إنتاج واسعة النطاق.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/نافذة-26',
      language: 'ar',
      postedAt: '2026-04-26T09:00:00.000Z',
      expiresAt: '2026-05-26T23:59:59.000Z',
    },
    {
      title: 'مطور Next.js',
      companyName: 'تقنية المعلومات',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مطور Next.js لبناء تطبيقات ويب عالية الأداء مع Server Side Rendering.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/تقنية-المعلومات-27',
      language: 'ar',
      postedAt: '2026-04-27T09:00:00.000Z',
      expiresAt: '2026-05-27T23:59:59.000Z',
    },
    {
      title: 'مهندس بيانات (Data Engineer)',
      companyName: 'ميزان',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'علم البيانات',
      description: 'فرصة لهندسة خطوط بيانات ضخمة باستخدام Spark وKafka في بيئة سحابية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/ميزان-28',
      language: 'ar',
      postedAt: '2026-04-28T09:00:00.000Z',
      expiresAt: '2026-05-28T23:59:59.000Z',
    },
    {
      title: 'مطور تكامل أنظمة',
      companyName: 'بصيرة',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في تكامل الأنظمة وبناء جسور البيانات بين المنصات المختلفة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/بصيرة-29',
      language: 'ar',
      postedAt: '2026-04-29T09:00:00.000Z',
      expiresAt: '2026-05-29T23:59:59.000Z',
    },
    {
      title: 'مدير تطوير برمجيات',
      companyName: 'روّاد',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'إدارة المنتجات',
      description: 'فرصة لقيادة فريق تطوير برمجيات وإدارة المشاريع التقنية من البداية للإطلاق.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/روّاد-30',
      language: 'ar',
      postedAt: '2026-04-30T09:00:00.000Z',
      expiresAt: '2026-05-30T23:59:59.000Z',
    },
    {
      title: 'مطور باك إند (Node.js)',
      companyName: 'شركة STC',
      source: 'لينكد إن',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description:
        'نبحث عن مطور باك إند متمكن من Node.js للانضمام إلى فريقنا التقني. يُشترط خبرة لا تقل عن ٣ سنوات في تطوير APIs وإدارة قواعد البيانات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/شركة-stc-31',
      language: 'ar',
      postedAt: '2026-05-01T09:00:00.000Z',
      expiresAt: '2026-05-31T23:59:59.000Z',
    },
    {
      title: 'مهندس واجهات أمامية (React)',
      companyName: 'أرامكو السعودية',
      source: 'وظف',
      location: 'JEDDAH',
      category: 'تطوير الواجهات الأمامية',
      description:
        'مطلوب مهندس React لتطوير واجهات مستخدم احترافية وسريعة الأداء ضمن فريق منتج متكامل.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/أرامكو-السعودية-32',
      language: 'ar',
      postedAt: '2026-05-02T09:00:00.000Z',
      expiresAt: '2026-06-01T23:59:59.000Z',
    },
    {
      title: 'مهندس DevOps',
      companyName: 'نيوم',
      source: 'جلاس دور',
      location: 'DAMMAM',
      category: 'البنية التحتية والعمليات',
      description:
        'فرصة للانضمام إلى فريق البنية التحتية. ستكون مسؤولاً عن إدارة خطوط CI/CD والنشر السحابي.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/نيوم-33',
      language: 'ar',
      postedAt: '2026-05-03T09:00:00.000Z',
      expiresAt: '2026-06-02T23:59:59.000Z',
    },
    {
      title: 'عالم بيانات',
      companyName: 'موبايلي',
      source: 'بيت',
      location: 'KHOBAR',
      category: 'علم البيانات',
      description:
        'فرصة مميزة لعالم بيانات متخصص في تحليل السلوك والنمذجة الإحصائية. خبرة في Python وSQL مطلوبة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/موبايلي-34',
      language: 'ar',
      postedAt: '2026-05-04T09:00:00.000Z',
      expiresAt: '2026-06-03T23:59:59.000Z',
    },
    {
      title: 'مصمم واجهات المستخدم (UI/UX)',
      companyName: 'stc pay',
      source: 'إنديد',
      location: 'MECCA',
      category: 'تصميم تجربة المستخدم',
      description: 'نبحث عن مصمم UI/UX مبدع لتصميم تجارب مستخدم سلسة لتطبيقات الويب والجوال.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/stc-pay-35',
      language: 'ar',
      postedAt: '2026-05-05T09:00:00.000Z',
      expiresAt: '2026-06-04T23:59:59.000Z',
    },
    {
      title: 'مطور تطبيقات جوال (Flutter)',
      companyName: 'نون',
      source: 'ناوكري غلف',
      location: 'MEDINA',
      category: 'تطوير تطبيقات الجوال',
      description: 'مطلوب مطور Flutter لبناء تطبيقات جوال عالية الأداء على منصتي iOS وAndroid.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/نون-36',
      language: 'ar',
      postedAt: '2026-05-06T09:00:00.000Z',
      expiresAt: '2026-06-05T23:59:59.000Z',
    },
    {
      title: 'محلل أمن معلومات',
      companyName: 'جرير',
      source: 'لينكد إن',
      location: 'TABUK',
      category: 'الأمن السيبراني',
      description:
        'نبحث عن محلل أمن معلومات لحماية البنية التحتية الرقمية من التهديدات السيبرانية المتطورة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/جرير-37',
      language: 'ar',
      postedAt: '2026-05-07T09:00:00.000Z',
      expiresAt: '2026-06-06T23:59:59.000Z',
    },
    {
      title: 'مهندس ضمان الجودة (Automation)',
      companyName: 'بنك الراجحي',
      source: 'وظف',
      location: 'RIYADH',
      category: 'ضمان الجودة',
      description:
        'مطلوب مهندس أتمتة اختبارات للعمل على تطبيقات حساسة. خبرة في Selenium أو Cypress مطلوبة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/بنك-الراجحي-38',
      language: 'ar',
      postedAt: '2026-05-08T09:00:00.000Z',
      expiresAt: '2026-06-07T23:59:59.000Z',
    },
    {
      title: 'مدير منتج تقني',
      companyName: 'سابك',
      source: 'جلاس دور',
      location: 'JEDDAH',
      category: 'إدارة المنتجات',
      description: 'فرصة لإدارة دورة حياة منتج تقني كاملة ضمن فريق متعدد التخصصات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/سابك-39',
      language: 'ar',
      postedAt: '2026-05-09T09:00:00.000Z',
      expiresAt: '2026-06-08T23:59:59.000Z',
    },
    {
      title: 'مطور فول ستاك',
      companyName: 'إلم',
      source: 'بيت',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'نبحث عن مطور Full Stack متمكن من React وNode.js للعمل على منصات رقمية متقدمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/إلم-40',
      language: 'ar',
      postedAt: '2026-05-10T09:00:00.000Z',
      expiresAt: '2026-06-09T23:59:59.000Z',
    },
    {
      title: 'مهندس سحابي (AWS)',
      companyName: 'يونيفونيك',
      source: 'إنديد',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'مطلوب مهندس AWS لتصميم وإدارة بنية تحتية سحابية موثوقة وقابلة للتوسع.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/يونيفونيك-41',
      language: 'ar',
      postedAt: '2026-05-11T09:00:00.000Z',
      expiresAt: '2026-06-10T23:59:59.000Z',
    },
    {
      title: 'مهندس تعلم آلي',
      companyName: 'فودكس',
      source: 'ناوكري غلف',
      location: 'MECCA',
      category: 'علم البيانات',
      description:
        'فرصة للعمل في تطوير نماذج تعلم آلي لتحسين تجربة المستخدم وتحليل البيانات الضخمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/فودكس-42',
      language: 'ar',
      postedAt: '2026-05-12T09:00:00.000Z',
      expiresAt: '2026-06-11T23:59:59.000Z',
    },
    {
      title: 'مطور Node.js',
      companyName: 'تمارا',
      source: 'لينكد إن',
      location: 'MEDINA',
      category: 'تطوير الواجهة الخلفية',
      description: 'نبحث عن مطور Node.js متمكن للعمل على خدمات الويب وتكاملات APIs.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/تمارا-43',
      language: 'ar',
      postedAt: '2026-05-13T09:00:00.000Z',
      expiresAt: '2026-06-12T23:59:59.000Z',
    },
    {
      title: 'مهندس TypeScript',
      companyName: 'تابي',
      source: 'وظف',
      location: 'TABUK',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مهندس TypeScript متمكن لتطوير حلول تقنية حديثة ضمن فريق متخصص.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/تابي-44',
      language: 'ar',
      postedAt: '2026-05-14T09:00:00.000Z',
      expiresAt: '2026-06-13T23:59:59.000Z',
    },
    {
      title: 'مدير قواعد بيانات',
      companyName: 'جيديا',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'علم البيانات',
      description:
        'مطلوب مدير قواعد بيانات متخصص في PostgreSQL لإدارة قواعد بيانات الأنظمة الحساسة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/جيديا-45',
      language: 'ar',
      postedAt: '2026-05-15T09:00:00.000Z',
      expiresAt: '2026-06-14T23:59:59.000Z',
    },
    {
      title: 'مهندس معماريات الأنظمة',
      companyName: 'ليان تكنولوجيز',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'هندسة البرمجيات',
      description: 'فرصة لتصميم معماريات أنظمة رقمية متقدمة تخدم ملايين المستخدمين.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/ليان-تكنولوجيز-46',
      language: 'ar',
      postedAt: '2026-05-16T09:00:00.000Z',
      expiresAt: '2026-06-15T23:59:59.000Z',
    },
    {
      title: 'مطور واجهات برمجية (API)',
      companyName: 'موزن',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'الأمن السيبراني',
      description: 'نوفر فرصة لمطور APIs في مجال الذكاء الاصطناعي والحلول التقنية المتقدمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/موزن-47',
      language: 'ar',
      postedAt: '2026-05-17T09:00:00.000Z',
      expiresAt: '2026-06-16T23:59:59.000Z',
    },
    {
      title: 'سكرام ماستر',
      companyName: 'إيجادة',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'إدارة المنتجات',
      description: 'مطلوب Scrum Master معتمد لقيادة فرق تطوير البرمجيات وفق منهجية أجايل.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/إيجادة-48',
      language: 'ar',
      postedAt: '2026-05-18T09:00:00.000Z',
      expiresAt: '2026-06-17T23:59:59.000Z',
    },
    {
      title: 'قائد تقني (Tech Lead)',
      companyName: 'سلة',
      source: 'لينكد إن',
      location: 'MECCA',
      category: 'تطوير تطبيقات الجوال',
      description: 'نبحث عن قائد تقني لقيادة فريق هندسة وتطوير منصات إلكترونية متكاملة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/سلة-49',
      language: 'ar',
      postedAt: '2026-05-19T09:00:00.000Z',
      expiresAt: '2026-06-18T23:59:59.000Z',
    },
    {
      title: 'مهندس برمجيات',
      companyName: 'زد',
      source: 'وظف',
      location: 'MEDINA',
      category: 'ضمان الجودة',
      description: 'انضم كمهندس برمجيات وساهم في بناء منصة تخدم آلاف المستخدمين يومياً.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/زد-50',
      language: 'ar',
      postedAt: '2026-05-20T09:00:00.000Z',
      expiresAt: '2026-06-19T23:59:59.000Z',
    },
    {
      title: 'مطور React Native',
      companyName: 'حسوب',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'تطوير تطبيقات الجوال',
      description: 'مطلوب مطور React Native لبناء تطبيقات جوال متعددة المنصات بأداء عالٍ.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/حسوب-51',
      language: 'ar',
      postedAt: '2026-05-21T09:00:00.000Z',
      expiresAt: '2026-06-20T23:59:59.000Z',
    },
    {
      title: 'مهندس أمن تطبيقات',
      companyName: 'كيان',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'الأمن السيبراني',
      description: 'فرصة للعمل في مجال أمن التطبيقات واختبار الاختراق لحماية المنصات الرقمية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/كيان-52',
      language: 'ar',
      postedAt: '2026-05-22T09:00:00.000Z',
      expiresAt: '2026-06-21T23:59:59.000Z',
    },
    {
      title: 'محلل بيانات (Power BI)',
      companyName: 'بيانات',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'علم البيانات',
      description:
        'مطلوب محلل بيانات متمكن من Power BI وExcel المتقدم لإنشاء تقارير تحليلية دقيقة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/بيانات-53',
      language: 'ar',
      postedAt: '2026-05-23T09:00:00.000Z',
      expiresAt: '2026-06-22T23:59:59.000Z',
    },
    {
      title: 'مطور Python',
      companyName: 'فاتورة',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'هندسة البرمجيات',
      description: 'نبحث عن مطور Python متمكن للعمل على أنظمة معالجة البيانات والأتمتة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/فاتورة-54',
      language: 'ar',
      postedAt: '2026-05-24T09:00:00.000Z',
      expiresAt: '2026-06-23T23:59:59.000Z',
    },
    {
      title: 'مصمم تجربة المستخدم (UX Research)',
      companyName: 'ثروة',
      source: 'لينكد إن',
      location: 'MECCA',
      category: 'تصميم تجربة المستخدم',
      description: 'مطلوب باحث UX لإجراء دراسات المستخدم وتحسين تجربة المنتجات الرقمية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/ثروة-55',
      language: 'ar',
      postedAt: '2026-05-25T09:00:00.000Z',
      expiresAt: '2026-06-24T23:59:59.000Z',
    },
    {
      title: 'مهندس Kubernetes',
      companyName: 'نافذة',
      source: 'وظف',
      location: 'TABUK',
      category: 'البنية التحتية والعمليات',
      description: 'فرصة للعمل مع Kubernetes وDocker في بيئة إنتاج واسعة النطاق.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/نافذة-56',
      language: 'ar',
      postedAt: '2026-05-26T09:00:00.000Z',
      expiresAt: '2026-06-25T23:59:59.000Z',
    },
    {
      title: 'مطور Next.js',
      companyName: 'تقنية المعلومات',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مطور Next.js لبناء تطبيقات ويب عالية الأداء مع Server Side Rendering.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/تقنية-المعلومات-57',
      language: 'ar',
      postedAt: '2026-05-27T09:00:00.000Z',
      expiresAt: '2026-06-26T23:59:59.000Z',
    },
    {
      title: 'مهندس بيانات (Data Engineer)',
      companyName: 'ميزان',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'علم البيانات',
      description: 'فرصة لهندسة خطوط بيانات ضخمة باستخدام Spark وKafka في بيئة سحابية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/ميزان-58',
      language: 'ar',
      postedAt: '2026-05-28T09:00:00.000Z',
      expiresAt: '2026-06-27T23:59:59.000Z',
    },
    {
      title: 'مطور تكامل أنظمة',
      companyName: 'بصيرة',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في تكامل الأنظمة وبناء جسور البيانات بين المنصات المختلفة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/بصيرة-59',
      language: 'ar',
      postedAt: '2026-05-29T09:00:00.000Z',
      expiresAt: '2026-06-28T23:59:59.000Z',
    },
    {
      title: 'مدير تطوير برمجيات',
      companyName: 'روّاد',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'إدارة المنتجات',
      description: 'فرصة لقيادة فريق تطوير برمجيات وإدارة المشاريع التقنية من البداية للإطلاق.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/روّاد-60',
      language: 'ar',
      postedAt: '2026-05-30T09:00:00.000Z',
      expiresAt: '2026-06-29T23:59:59.000Z',
    },
    {
      title: 'مطور GraphQL',
      companyName: 'مدى',
      source: 'لينكد إن',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في GraphQL لبناء APIs مرنة وفعالة لتطبيقات الويب والجوال.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/مدى-61',
      language: 'ar',
      postedAt: '2026-04-21T09:00:00.000Z',
      expiresAt: '2026-05-21T23:59:59.000Z',
    },
    {
      title: 'مهندس أداء الأنظمة',
      companyName: 'هيئة الاتصالات',
      source: 'وظف',
      location: 'JEDDAH',
      category: 'البنية التحتية والعمليات',
      description: 'فرصة للعمل على تحسين أداء وسرعة الأنظمة والتطبيقات في بيئة إنتاج واسعة النطاق.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/هيئة-الاتصالات-62',
      language: 'ar',
      postedAt: '2026-04-22T09:00:00.000Z',
      expiresAt: '2026-05-22T23:59:59.000Z',
    },
    {
      title: 'مطور Microservices',
      companyName: 'أبشر',
      source: 'جلاس دور',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'نبحث عن مطور متمكن في بناء معماريات Microservices باستخدام Docker وKubernetes.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/أبشر-63',
      language: 'ar',
      postedAt: '2026-04-23T09:00:00.000Z',
      expiresAt: '2026-05-23T23:59:59.000Z',
    },
    {
      title: 'محلل ذكاء اصطناعي',
      companyName: 'بيكالي',
      source: 'بيت',
      location: 'KHOBAR',
      category: 'علم البيانات',
      description:
        'فرصة للعمل في تحليل وتطوير نماذج الذكاء الاصطناعي وتطبيقها على البيانات الضخمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/بيكالي-64',
      language: 'ar',
      postedAt: '2026-04-24T09:00:00.000Z',
      expiresAt: '2026-05-24T23:59:59.000Z',
    },
    {
      title: 'مصمم هوية بصرية',
      companyName: 'ممشى',
      source: 'إنديد',
      location: 'MECCA',
      category: 'تصميم تجربة المستخدم',
      description: 'نبحث عن مصمم هوية بصرية لتصميم هويات بصرية إبداعية لمنصات وتطبيقات رقمية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/ممشى-65',
      language: 'ar',
      postedAt: '2026-04-25T09:00:00.000Z',
      expiresAt: '2026-05-25T23:59:59.000Z',
    },
    {
      title: 'مطور Ionic',
      companyName: 'واجد',
      source: 'ناوكري غلف',
      location: 'MEDINA',
      category: 'تطوير تطبيقات الجوال',
      description: 'مطلوب مطور Ionic لبناء تطبيقات هجينة عالية الأداء للجوال بتجربة مستخدم متميزة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/واجد-66',
      language: 'ar',
      postedAt: '2026-04-26T09:00:00.000Z',
      expiresAt: '2026-05-26T23:59:59.000Z',
    },
    {
      title: 'مختبر اختراق (Penetration Tester)',
      companyName: 'ثمانية',
      source: 'لينكد إن',
      location: 'TABUK',
      category: 'الأمن السيبراني',
      description: 'فرصة للعمل في اختبار الاختراق وكشف الثغرات الأمنية في الأنظمة والتطبيقات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/ثمانية-67',
      language: 'ar',
      postedAt: '2026-04-27T09:00:00.000Z',
      expiresAt: '2026-05-27T23:59:59.000Z',
    },
    {
      title: 'مهندس أتمتة اختبارات',
      companyName: 'منصة أبدأ',
      source: 'وظف',
      location: 'RIYADH',
      category: 'ضمان الجودة',
      description: 'نبحث عن مهندس متخصص في أتمتة اختبارات الواجهات والـ APIs باستخدام أدوات حديثة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/منصة-أبدأ-68',
      language: 'ar',
      postedAt: '2026-04-28T09:00:00.000Z',
      expiresAt: '2026-05-28T23:59:59.000Z',
    },
    {
      title: 'أخصائي إدارة مشاريع تقنية',
      companyName: 'خمسة',
      source: 'جلاس دور',
      location: 'JEDDAH',
      category: 'إدارة المنتجات',
      description: 'فرصة لإدارة مشاريع تقنية متعددة وضمان تسليمها في الوقت المحدد وبجودة عالية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/خمسة-69',
      language: 'ar',
      postedAt: '2026-04-29T09:00:00.000Z',
      expiresAt: '2026-05-29T23:59:59.000Z',
    },
    {
      title: 'مطور Express.js',
      companyName: 'مشاريع',
      source: 'بيت',
      location: 'DAMMAM',
      category: 'تطوير الواجهة الخلفية',
      description: 'نبحث عن مطور Express.js لبناء خوادم ويب قابلة للتوسع مع هيكلية نظيفة ومنظمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/مشاريع-70',
      language: 'ar',
      postedAt: '2026-04-30T09:00:00.000Z',
      expiresAt: '2026-05-30T23:59:59.000Z',
    },
    {
      title: 'مهندس Redis وCaching',
      companyName: 'تواصل',
      source: 'إنديد',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'مطلوب مهندس متخصص في Redis وحلول التخزين المؤقت لتحسين أداء التطبيقات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/تواصل-71',
      language: 'ar',
      postedAt: '2026-05-01T09:00:00.000Z',
      expiresAt: '2026-05-31T23:59:59.000Z',
    },
    {
      title: 'مطور TensorFlow',
      companyName: 'رقمي',
      source: 'ناوكري غلف',
      location: 'MECCA',
      category: 'علم البيانات',
      description: 'فرصة للعمل في تطوير نماذج TensorFlow لتطبيقات التعلم العميق ومعالجة الصور.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/رقمي-72',
      language: 'ar',
      postedAt: '2026-05-02T09:00:00.000Z',
      expiresAt: '2026-06-01T23:59:59.000Z',
    },
    {
      title: 'مطور Vue.js',
      companyName: 'نبتة',
      source: 'لينكد إن',
      location: 'MEDINA',
      category: 'تطوير الواجهات الأمامية',
      description: 'مطلوب مطور Vue.js لبناء واجهات مستخدم تفاعلية وسريعة لمنصات الويب.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/نبتة-73',
      language: 'ar',
      postedAt: '2026-05-03T09:00:00.000Z',
      expiresAt: '2026-06-02T23:59:59.000Z',
    },
    {
      title: 'مهندس شبكات',
      companyName: 'سفر',
      source: 'وظف',
      location: 'TABUK',
      category: 'البنية التحتية والعمليات',
      description: 'نبحث عن مهندس شبكات لتصميم وإدارة البنية التحتية للشبكات في بيئة سحابية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/سفر-74',
      language: 'ar',
      postedAt: '2026-05-04T09:00:00.000Z',
      expiresAt: '2026-06-03T23:59:59.000Z',
    },
    {
      title: 'مطور Prisma ORM',
      companyName: 'مسار',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل مع Prisma ORM وPostgreSQL في بناء طبقات بيانات آمنة وفعالة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/مسار-75',
      language: 'ar',
      postedAt: '2026-05-05T09:00:00.000Z',
      expiresAt: '2026-06-04T23:59:59.000Z',
    },
    {
      title: 'محلل متطلبات تقنية',
      companyName: 'ذهب',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'إدارة المنتجات',
      description: 'نبحث عن محلل متطلبات لترجمة احتياجات الأعمال إلى مواصفات تقنية واضحة ودقيقة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/ذهب-76',
      language: 'ar',
      postedAt: '2026-05-06T09:00:00.000Z',
      expiresAt: '2026-06-05T23:59:59.000Z',
    },
    {
      title: 'مطور Elasticsearch',
      companyName: 'إتقان',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في Elasticsearch لبناء محركات بحث سريعة وفعالة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/إتقان-77',
      language: 'ar',
      postedAt: '2026-05-07T09:00:00.000Z',
      expiresAt: '2026-06-06T23:59:59.000Z',
    },
    {
      title: 'مهندس CI/CD',
      companyName: 'نهضة',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'فرصة لبناء وإدارة خطوط CI/CD باستخدام GitHub Actions وJenkins في بيئات متعددة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/نهضة-78',
      language: 'ar',
      postedAt: '2026-05-08T09:00:00.000Z',
      expiresAt: '2026-06-07T23:59:59.000Z',
    },
    {
      title: 'مطور تجارة إلكترونية',
      companyName: 'أفق',
      source: 'لينكد إن',
      location: 'MECCA',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في بناء منصات تجارة إلكترونية متكاملة مع بوابات الدفع.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/أفق-79',
      language: 'ar',
      postedAt: '2026-05-09T09:00:00.000Z',
      expiresAt: '2026-06-08T23:59:59.000Z',
    },
    {
      title: 'مهندس أمن السحابة',
      companyName: 'ريادة',
      source: 'وظف',
      location: 'MEDINA',
      category: 'الأمن السيبراني',
      description:
        'فرصة للعمل في تأمين البنية التحتية السحابية وتطبيق معايير الأمن على AWS وAzure.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/ريادة-80',
      language: 'ar',
      postedAt: '2026-05-10T09:00:00.000Z',
      expiresAt: '2026-06-09T23:59:59.000Z',
    },
    {
      title: 'مطور Tailwind CSS',
      companyName: 'ابتكار',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مطور متمكن من Tailwind CSS لبناء واجهات مستخدم جميلة ومتجاوبة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/ابتكار-81',
      language: 'ar',
      postedAt: '2026-05-11T09:00:00.000Z',
      expiresAt: '2026-06-10T23:59:59.000Z',
    },
    {
      title: 'مهندس WebSocket',
      companyName: 'إشراق',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'تطوير الواجهة الخلفية',
      description: 'مطلوب مهندس متخصص في WebSocket وتطبيقات الوقت الفعلي مثل الدردشة والإشعارات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/إشراق-82',
      language: 'ar',
      postedAt: '2026-05-12T09:00:00.000Z',
      expiresAt: '2026-06-11T23:59:59.000Z',
    },
    {
      title: 'مطور Stripe Integration',
      companyName: 'تحول',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل في تكامل بوابات الدفع Stripe وغيرها مع تطبيقات الويب والجوال.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/تحول-83',
      language: 'ar',
      postedAt: '2026-05-13T09:00:00.000Z',
      expiresAt: '2026-06-12T23:59:59.000Z',
    },
    {
      title: 'محلل أعمال تقنية',
      companyName: 'نور',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'إدارة المنتجات',
      description: 'نبحث عن محلل أعمال لدعم الفرق التقنية في فهم احتياجات السوق وتحسين المنتجات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/نور-84',
      language: 'ar',
      postedAt: '2026-05-14T09:00:00.000Z',
      expiresAt: '2026-06-13T23:59:59.000Z',
    },
    {
      title: 'مطور JWT وAuth',
      companyName: 'مبادرة',
      source: 'لينكد إن',
      location: 'TABUK',
      category: 'الأمن السيبراني',
      description: 'مطلوب مطور متخصص في أنظمة المصادقة JWT وOAuth 2.0 لتأمين التطبيقات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/مبادرة-85',
      language: 'ar',
      postedAt: '2026-05-15T09:00:00.000Z',
      expiresAt: '2026-06-14T23:59:59.000Z',
    },
    {
      title: 'مهندس MongoDB',
      companyName: 'توسع',
      source: 'وظف',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل مع MongoDB في بناء قواعد بيانات مرنة لتطبيقات الويب الحديثة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/توسع-86',
      language: 'ar',
      postedAt: '2026-05-16T09:00:00.000Z',
      expiresAt: '2026-06-15T23:59:59.000Z',
    },
    {
      title: 'مطور Svelte',
      companyName: 'أصالة',
      source: 'جلاس دور',
      location: 'JEDDAH',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مطور Svelte لبناء واجهات ويب خفيفة الوزن وعالية الأداء.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/أصالة-87',
      language: 'ar',
      postedAt: '2026-05-17T09:00:00.000Z',
      expiresAt: '2026-06-16T23:59:59.000Z',
    },
    {
      title: 'مهندس بنية بيانات',
      companyName: 'تقدم',
      source: 'بيت',
      location: 'DAMMAM',
      category: 'علم البيانات',
      description: 'فرصة لتصميم وتحسين هياكل البيانات وقواعد البيانات لأنظمة عالية التحميل.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/تقدم-88',
      language: 'ar',
      postedAt: '2026-05-18T09:00:00.000Z',
      expiresAt: '2026-06-17T23:59:59.000Z',
    },
    {
      title: 'مطور Serverless',
      companyName: 'بناء',
      source: 'إنديد',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'مطلوب مطور Serverless للعمل على Lambda وCloud Functions في بيئات سحابية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/بناء-89',
      language: 'ar',
      postedAt: '2026-05-19T09:00:00.000Z',
      expiresAt: '2026-06-18T23:59:59.000Z',
    },
    {
      title: 'مطور تكامل ERP',
      companyName: 'وصول',
      source: 'ناوكري غلف',
      location: 'MECCA',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل في تكامل أنظمة ERP مع التطبيقات الرقمية وبناء جسور البيانات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/وصول-90',
      language: 'ar',
      postedAt: '2026-05-20T09:00:00.000Z',
      expiresAt: '2026-06-19T23:59:59.000Z',
    },
    {
      title: 'مطور GraphQL',
      companyName: 'مدى',
      source: 'لينكد إن',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في GraphQL لبناء APIs مرنة وفعالة لتطبيقات الويب والجوال.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/مدى-91',
      language: 'ar',
      postedAt: '2026-05-21T09:00:00.000Z',
      expiresAt: '2026-06-20T23:59:59.000Z',
    },
    {
      title: 'مهندس أداء الأنظمة',
      companyName: 'هيئة الاتصالات',
      source: 'وظف',
      location: 'JEDDAH',
      category: 'البنية التحتية والعمليات',
      description: 'فرصة للعمل على تحسين أداء وسرعة الأنظمة والتطبيقات في بيئة إنتاج واسعة النطاق.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/هيئة-الاتصالات-92',
      language: 'ar',
      postedAt: '2026-05-22T09:00:00.000Z',
      expiresAt: '2026-06-21T23:59:59.000Z',
    },
    {
      title: 'مطور Microservices',
      companyName: 'أبشر',
      source: 'جلاس دور',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'نبحث عن مطور متمكن في بناء معماريات Microservices باستخدام Docker وKubernetes.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/أبشر-93',
      language: 'ar',
      postedAt: '2026-05-23T09:00:00.000Z',
      expiresAt: '2026-06-22T23:59:59.000Z',
    },
    {
      title: 'محلل ذكاء اصطناعي',
      companyName: 'بيكالي',
      source: 'بيت',
      location: 'KHOBAR',
      category: 'علم البيانات',
      description:
        'فرصة للعمل في تحليل وتطوير نماذج الذكاء الاصطناعي وتطبيقها على البيانات الضخمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/بيكالي-94',
      language: 'ar',
      postedAt: '2026-05-24T09:00:00.000Z',
      expiresAt: '2026-06-23T23:59:59.000Z',
    },
    {
      title: 'مصمم هوية بصرية',
      companyName: 'ممشى',
      source: 'إنديد',
      location: 'MECCA',
      category: 'تصميم تجربة المستخدم',
      description: 'نبحث عن مصمم هوية بصرية لتصميم هويات بصرية إبداعية لمنصات وتطبيقات رقمية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/ممشى-95',
      language: 'ar',
      postedAt: '2026-05-25T09:00:00.000Z',
      expiresAt: '2026-06-24T23:59:59.000Z',
    },
    {
      title: 'مطور Ionic',
      companyName: 'واجد',
      source: 'ناوكري غلف',
      location: 'MEDINA',
      category: 'تطوير تطبيقات الجوال',
      description: 'مطلوب مطور Ionic لبناء تطبيقات هجينة عالية الأداء للجوال بتجربة مستخدم متميزة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/واجد-96',
      language: 'ar',
      postedAt: '2026-05-26T09:00:00.000Z',
      expiresAt: '2026-06-25T23:59:59.000Z',
    },
    {
      title: 'مختبر اختراق (Penetration Tester)',
      companyName: 'ثمانية',
      source: 'لينكد إن',
      location: 'TABUK',
      category: 'الأمن السيبراني',
      description: 'فرصة للعمل في اختبار الاختراق وكشف الثغرات الأمنية في الأنظمة والتطبيقات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/ثمانية-97',
      language: 'ar',
      postedAt: '2026-05-27T09:00:00.000Z',
      expiresAt: '2026-06-26T23:59:59.000Z',
    },
    {
      title: 'مهندس أتمتة اختبارات',
      companyName: 'منصة أبدأ',
      source: 'وظف',
      location: 'RIYADH',
      category: 'ضمان الجودة',
      description: 'نبحث عن مهندس متخصص في أتمتة اختبارات الواجهات والـ APIs باستخدام أدوات حديثة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/منصة-أبدأ-98',
      language: 'ar',
      postedAt: '2026-05-28T09:00:00.000Z',
      expiresAt: '2026-06-27T23:59:59.000Z',
    },
    {
      title: 'أخصائي إدارة مشاريع تقنية',
      companyName: 'خمسة',
      source: 'جلاس دور',
      location: 'JEDDAH',
      category: 'إدارة المنتجات',
      description: 'فرصة لإدارة مشاريع تقنية متعددة وضمان تسليمها في الوقت المحدد وبجودة عالية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/خمسة-99',
      language: 'ar',
      postedAt: '2026-05-29T09:00:00.000Z',
      expiresAt: '2026-06-28T23:59:59.000Z',
    },
    {
      title: 'مطور Express.js',
      companyName: 'مشاريع',
      source: 'بيت',
      location: 'DAMMAM',
      category: 'تطوير الواجهة الخلفية',
      description: 'نبحث عن مطور Express.js لبناء خوادم ويب قابلة للتوسع مع هيكلية نظيفة ومنظمة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/مشاريع-100',
      language: 'ar',
      postedAt: '2026-05-30T09:00:00.000Z',
      expiresAt: '2026-06-29T23:59:59.000Z',
    },
    {
      title: 'مهندس Redis وCaching',
      companyName: 'تواصل',
      source: 'إنديد',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'مطلوب مهندس متخصص في Redis وحلول التخزين المؤقت لتحسين أداء التطبيقات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/تواصل-101',
      language: 'ar',
      postedAt: '2026-05-31T09:00:00.000Z',
      expiresAt: '2026-06-30T23:59:59.000Z',
    },
    {
      title: 'مطور TensorFlow',
      companyName: 'رقمي',
      source: 'ناوكري غلف',
      location: 'MECCA',
      category: 'علم البيانات',
      description: 'فرصة للعمل في تطوير نماذج TensorFlow لتطبيقات التعلم العميق ومعالجة الصور.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/رقمي-102',
      language: 'ar',
      postedAt: '2026-06-01T09:00:00.000Z',
      expiresAt: '2026-07-01T23:59:59.000Z',
    },
    {
      title: 'مطور Vue.js',
      companyName: 'نبتة',
      source: 'لينكد إن',
      location: 'MEDINA',
      category: 'تطوير الواجهات الأمامية',
      description: 'مطلوب مطور Vue.js لبناء واجهات مستخدم تفاعلية وسريعة لمنصات الويب.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/نبتة-103',
      language: 'ar',
      postedAt: '2026-06-02T09:00:00.000Z',
      expiresAt: '2026-07-02T23:59:59.000Z',
    },
    {
      title: 'مهندس شبكات',
      companyName: 'سفر',
      source: 'وظف',
      location: 'TABUK',
      category: 'البنية التحتية والعمليات',
      description: 'نبحث عن مهندس شبكات لتصميم وإدارة البنية التحتية للشبكات في بيئة سحابية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/سفر-104',
      language: 'ar',
      postedAt: '2026-06-03T09:00:00.000Z',
      expiresAt: '2026-07-03T23:59:59.000Z',
    },
    {
      title: 'مطور Prisma ORM',
      companyName: 'مسار',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل مع Prisma ORM وPostgreSQL في بناء طبقات بيانات آمنة وفعالة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/مسار-105',
      language: 'ar',
      postedAt: '2026-06-04T09:00:00.000Z',
      expiresAt: '2026-07-04T23:59:59.000Z',
    },
    {
      title: 'محلل متطلبات تقنية',
      companyName: 'ذهب',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'إدارة المنتجات',
      description: 'نبحث عن محلل متطلبات لترجمة احتياجات الأعمال إلى مواصفات تقنية واضحة ودقيقة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/ذهب-106',
      language: 'ar',
      postedAt: '2026-06-05T09:00:00.000Z',
      expiresAt: '2026-07-05T23:59:59.000Z',
    },
    {
      title: 'مطور Elasticsearch',
      companyName: 'إتقان',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في Elasticsearch لبناء محركات بحث سريعة وفعالة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/إتقان-107',
      language: 'ar',
      postedAt: '2026-06-06T09:00:00.000Z',
      expiresAt: '2026-07-06T23:59:59.000Z',
    },
    {
      title: 'مهندس CI/CD',
      companyName: 'نهضة',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'فرصة لبناء وإدارة خطوط CI/CD باستخدام GitHub Actions وJenkins في بيئات متعددة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/نهضة-108',
      language: 'ar',
      postedAt: '2026-06-07T09:00:00.000Z',
      expiresAt: '2026-07-07T23:59:59.000Z',
    },
    {
      title: 'مطور تجارة إلكترونية',
      companyName: 'أفق',
      source: 'لينكد إن',
      location: 'MECCA',
      category: 'هندسة البرمجيات',
      description: 'مطلوب مطور متخصص في بناء منصات تجارة إلكترونية متكاملة مع بوابات الدفع.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/أفق-109',
      language: 'ar',
      postedAt: '2026-06-08T09:00:00.000Z',
      expiresAt: '2026-07-08T23:59:59.000Z',
    },
    {
      title: 'مهندس أمن السحابة',
      companyName: 'ريادة',
      source: 'وظف',
      location: 'MEDINA',
      category: 'الأمن السيبراني',
      description:
        'فرصة للعمل في تأمين البنية التحتية السحابية وتطبيق معايير الأمن على AWS وAzure.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/ريادة-110',
      language: 'ar',
      postedAt: '2026-06-09T09:00:00.000Z',
      expiresAt: '2026-07-09T23:59:59.000Z',
    },
    {
      title: 'مطور Tailwind CSS',
      companyName: 'ابتكار',
      source: 'جلاس دور',
      location: 'RIYADH',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مطور متمكن من Tailwind CSS لبناء واجهات مستخدم جميلة ومتجاوبة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/ابتكار-111',
      language: 'ar',
      postedAt: '2026-06-10T09:00:00.000Z',
      expiresAt: '2026-07-10T23:59:59.000Z',
    },
    {
      title: 'مهندس WebSocket',
      companyName: 'إشراق',
      source: 'بيت',
      location: 'JEDDAH',
      category: 'تطوير الواجهة الخلفية',
      description: 'مطلوب مهندس متخصص في WebSocket وتطبيقات الوقت الفعلي مثل الدردشة والإشعارات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/إشراق-112',
      language: 'ar',
      postedAt: '2026-06-11T09:00:00.000Z',
      expiresAt: '2026-07-11T23:59:59.000Z',
    },
    {
      title: 'مطور Stripe Integration',
      companyName: 'تحول',
      source: 'إنديد',
      location: 'DAMMAM',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل في تكامل بوابات الدفع Stripe وغيرها مع تطبيقات الويب والجوال.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/تحول-113',
      language: 'ar',
      postedAt: '2026-06-12T09:00:00.000Z',
      expiresAt: '2026-07-12T23:59:59.000Z',
    },
    {
      title: 'محلل أعمال تقنية',
      companyName: 'نور',
      source: 'ناوكري غلف',
      location: 'KHOBAR',
      category: 'إدارة المنتجات',
      description: 'نبحث عن محلل أعمال لدعم الفرق التقنية في فهم احتياجات السوق وتحسين المنتجات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/نور-114',
      language: 'ar',
      postedAt: '2026-06-13T09:00:00.000Z',
      expiresAt: '2026-07-13T23:59:59.000Z',
    },
    {
      title: 'مطور JWT وAuth',
      companyName: 'مبادرة',
      source: 'لينكد إن',
      location: 'TABUK',
      category: 'الأمن السيبراني',
      description: 'مطلوب مطور متخصص في أنظمة المصادقة JWT وOAuth 2.0 لتأمين التطبيقات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://linkedin.com/jobs/مبادرة-115',
      language: 'ar',
      postedAt: '2026-06-14T09:00:00.000Z',
      expiresAt: '2026-07-14T23:59:59.000Z',
    },
    {
      title: 'مهندس MongoDB',
      companyName: 'توسع',
      source: 'وظف',
      location: 'RIYADH',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل مع MongoDB في بناء قواعد بيانات مرنة لتطبيقات الويب الحديثة.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://wuzzuf.com/jobs/توسع-116',
      language: 'ar',
      postedAt: '2026-06-15T09:00:00.000Z',
      expiresAt: '2026-07-15T23:59:59.000Z',
    },
    {
      title: 'مطور Svelte',
      companyName: 'أصالة',
      source: 'جلاس دور',
      location: 'JEDDAH',
      category: 'تطوير الواجهات الأمامية',
      description: 'نبحث عن مطور Svelte لبناء واجهات ويب خفيفة الوزن وعالية الأداء.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://glassdoor.com/jobs/أصالة-117',
      language: 'ar',
      postedAt: '2026-06-16T09:00:00.000Z',
      expiresAt: '2026-07-16T23:59:59.000Z',
    },
    {
      title: 'مهندس بنية بيانات',
      companyName: 'تقدم',
      source: 'بيت',
      location: 'DAMMAM',
      category: 'علم البيانات',
      description: 'فرصة لتصميم وتحسين هياكل البيانات وقواعد البيانات لأنظمة عالية التحميل.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://bayt.com/jobs/تقدم-118',
      language: 'ar',
      postedAt: '2026-06-17T09:00:00.000Z',
      expiresAt: '2026-07-17T23:59:59.000Z',
    },
    {
      title: 'مطور Serverless',
      companyName: 'بناء',
      source: 'إنديد',
      location: 'KHOBAR',
      category: 'البنية التحتية والعمليات',
      description: 'مطلوب مطور Serverless للعمل على Lambda وCloud Functions في بيئات سحابية.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://indeed.com/jobs/بناء-119',
      language: 'ar',
      postedAt: '2026-06-18T09:00:00.000Z',
      expiresAt: '2026-07-18T23:59:59.000Z',
    },
    {
      title: 'مطور تكامل ERP',
      companyName: 'وصول',
      source: 'ناوكري غلف',
      location: 'MECCA',
      category: 'هندسة البرمجيات',
      description: 'فرصة للعمل في تكامل أنظمة ERP مع التطبيقات الرقمية وبناء جسور البيانات.',
      hrEmail: 'mohameddkaram@gmail.com',
      sourceUrl: 'https://naukrigulf.com/jobs/وصول-120',
      language: 'ar',
      postedAt: '2026-06-19T09:00:00.000Z',
      expiresAt: '2026-07-19T23:59:59.000Z',
    },
  ];

  await prisma.job.createMany({ data: jobs, skipDuplicates: true });
  console.log(`Seeded ${jobs.length} job records successfully.`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
