-- CreateEnum
CREATE TYPE "JobQualification" AS ENUM ('HIGH_SCHOOL', 'DIPLOMA', 'BACHELOR', 'MASTER', 'PHD', 'OTHER');

-- CreateEnum
CREATE TYPE "JobSpecialization" AS ENUM ('ENGINEERING', 'INFORMATION_TECHNOLOGY', 'BUSINESS_ADMINISTRATION', 'ACCOUNTING_FINANCE', 'MARKETING_SALES', 'HEALTHCARE', 'EDUCATION', 'HUMAN_RESOURCES', 'OTHER');

-- AlterTable
ALTER TABLE "jobs" ADD COLUMN     "qualification" "JobQualification" NOT NULL DEFAULT 'OTHER',
ADD COLUMN     "specialization" "JobSpecialization" NOT NULL DEFAULT 'OTHER';
