import { WebSiteConfig, ApiSourceConfig } from './scraper.types';

export const SITES_CONFIG: (WebSiteConfig | ApiSourceConfig)[] = [
  {
    name: 'ewdifh',
    type: 'web',
    url: 'https://www.ewdifh.com/category/corporate-jobs',
    baseUrl: 'https://www.ewdifh.com',
    jobLinkSelector: 'div.grid a[href*="/jobs/"]',
    jobContentSelector: 'div.card-body',
  },
  {
    name: 'twitter',
    type: 'api',
    apiUrl: 'https://api.getxapi.com/twitter/tweet/advanced_search',
    verifyUrl: 'https://api.getxapi.com/account/me',
    searchPhrases: [
      'وظائف شاغرة',
      'وظائف شاغره',
      'وظايف شاغرة',
      'وظايف شاغره',
      'شاغر وظيفي',
      'شاغر وظيفى',
      'شاغر وظيفه',
      'شاغر وظيفة',
      'فرص عمل',
      'فرصه عمل',
      'فرصة عمل',
      'توظيف فوري',
      'توظيف فورى',
      'مطلوب موظفين',
      'مطلوب موظفينه',
      'احتاج وظيفة',
      'احتاج وظيفه',
      'احتاج وظيفةً',
      'أحتاج وظيفة',
      'اعلان وظيفة',
      'إعلان وظيفة',
      'اعلان وظيفي',
      'إعلان وظيفي',
      'شواغر وظيفية',
      'شواغر وظيفيه',
      'وظائف اليوم',
      'وظائف اليومه',
      'وظائف عاجلة',
      'وظائف عاجله',
    ],
    authToken: process.env.GETXAPI_KEY || '',
  },
  {
    name: 'wadifh',
    type: 'web',
    url: 'https://www.jobs-1.com/jobs/archive/8', // صفحة الوظائف الشركات
    baseUrl: 'https://www.jobs-1.com',

    jobLinkSelector: 'div.bl-news-item a[href*="www.jobs-1.com/1"]',

    jobContentSelector: 'div.bl-detail-page',
  },
  {
    name: 'linkedksa',
    type: 'web',
    url: 'https://linkedksa.com',
    baseUrl: 'https://linkedksa.com',
    jobLinkSelector: 'div.uc_post_list_box a[href*="linkedksa.com/"]',
    jobContentSelector: '.elementor-widget-theme-post-content .elementor-widget-container',
  },
  {
    name: 'tabiwazifa',
    type: 'web',
    url: 'https://wazaef.net/jobs/category/%D9%88%D8%B8%D8%A7%D8%A6%D9%81-%D8%B4%D8%B1%D9%83%D8%A7%D8%AA',
    baseUrl: 'https://wazaef.net',
    jobLinkSelector:
      '.entry-list-item .entry-content-wrap .entry-header .entry-title a[href*="wazaef.net/jobs"]',
    jobContentSelector: '.elementor-widget-container',
  },
  {
    name: 'jbscv',
    type: 'web',
    url: 'https://jbscv.com/jobs',
    baseUrl: 'https://jbscv.com',
    jobLinkSelector: 'li.job_listing a[href*="/jobs/"]',
    jobContentSelector: 'div.job_description, div.application_details',
    ajaxConfig: {
      endpoint: 'https://jbscv.com/jm-ajax/get_listings/',
      params: {
        action: 'get_listings',
        lang: '',
        per_page: '50',
        orderby: 'desc',
        order: 'DESC',
        page: '1',
        show_pagination: 'false',
        post_id: '25709',
        'filter_job_type[]': 'remote',
        search_keywords: '',
        search_location: '',
        search_region: '0',
      },
    },
  },
  {
    name: 'fu1sa',
    type: 'web',
    url: 'https://fu1sa.com/jobs/category/%D9%88%D8%B8%D8%A7%D8%A6%D9%81-%D8%B4%D8%B1%D9%83%D8%A7%D8%AA/',
    baseUrl: 'https://fu1sa.com',
    jobLinkSelector: '.entry-title a',
    jobContentSelector: '.entry-content .card-body',
  },
  {
    name: 'alwzifa',
    type: 'web',
    url: 'https://alwzifa.com',
    baseUrl: 'https://alwzifa.com',
    jobLinkSelector: '.post-title',
    jobContentSelector: '.single-container article .entry-content',
  },
  {
    name: 'jobhuna',
    type: 'web',
    url: 'https://jobhuna.com',
    baseUrl: 'https://jobhuna.com',
    jobLinkSelector: '.entry-title a',
    jobContentSelector: '.entry-content',
  },
];

export const VALID_LOCATIONS = [
  'RIYADH',
  'AL_KHARJ',
  'AL_DAWADIMI',
  'AL_MAJMAAH',
  'AL_QUWAYIYAH',
  'WADI_AD_DAWASIR',
  'AL_AFLAJ',
  'AL_ZULFI',
  'SHAQRA',
  'AFIF',
  'AS_SULAYYIL',
  'MECCA',
  'JEDDAH',
  'TAIF',
  'AL_QUNFUDHAH',
  'RABIGH',
  'AL_LAYTH',
  'KHULAIS',
  'MEDINA',
  'YANBU',
  'AL_ULA',
  'MAHAD_AD_DAHAB',
  'BADR',
  'KHAYBAR',
  'BURAYDAH',
  'UNAIZAH',
  'AL_RASS',
  'AL_MITHNAB',
  'ASH_SHAMASIYAH',
  'DAMMAM',
  'KHOBAR',
  'AL_AHSA',
  'JUBAIL',
  'QATIF',
  'HAFR_AL_BATIN',
  'AL_KHAFJI',
  'ABHA',
  'KHAMIS_MUSHAIT',
  'BISHA',
  'AL_NAMAS',
  'MAHAYIL_ASIR',
  'TABUK',
  'DUBA',
  'TAYMA',
  'AL_WAJH',
  'UMLUJ',
  'HAIL',
  'BAQAA',
  'AL_GHAZALAH',
  'SAMIRA',
  'ARAR',
  'RAFHA',
  'TURAIF',
  'JIZAN',
  'SABYA',
  'ABU_ARISH',
  'SAMTAH',
  'BAISH',
  'NAJRAN',
  'SHARURAH',
  'BAHA',
  'BALJURASHI',
  'AL_MAKHWAH',
  'SAKAKA',
  'DUMAT_AL_JANDAL',
  'QURAYYAT',
  'OTHER',
] as const;

export const JOB_RESPONSE_SCHEMA = {
  type: 'ARRAY',
  items: {
    type: 'OBJECT',
    properties: {
      title: { type: 'STRING', description: 'عنوان الوظيفة', nullable: false },
      companyName: { type: 'STRING', description: 'اسم الشركة', nullable: false },
      location: {
        type: 'STRING',
        description:
          'ONE of: RIYADH, AL_KHARJ, AL_DAWADIMI, AL_MAJMAAH, AL_QUWAYIYAH, WADI_AD_DAWASIR, AL_AFLAJ, AL_ZULFI, SHAQRA, AFIF, AS_SULAYYIL, MECCA, JEDDAH, TAIF, AL_QUNFUDHAH, RABIGH, AL_LAYTH, KHULAIS, MEDINA, YANBU, AL_ULA, MAHAD_AD_DAHAB, BADR, KHAYBAR, BURAYDAH, UNAIZAH, AL_RASS, AL_MITHNAB, ASH_SHAMASIYAH, DAMMAM, KHOBAR, AL_AHSA, JUBAIL, QATIF, HAFR_AL_BATIN, AL_KHAFJI, ABHA, Khamis_Mushait, Bisha, Al_Namas, Mahayil_Asir, TABUK, DUBA, TAYMA, AL_WAJH, UMLUJ, HAIL, BAQAA, AL_GHAZALAH, SAMIRA, ARAR, RAFHA, TURAIF, JIZAN, SABYA, ABU_ARISH, SAMTAH, BAISH, NAJRAN, SHARURAH, BAHA, BALJURASHI, AL_MAKHWAH, SAKAKA, DUMAT_AL_JANDAL, QURAYYAT, OTHER',
        nullable: false,
      },
      hrEmail: {
        type: 'STRING',
        description: 'HR/contact email if found, otherwise null',
        nullable: true,
      },
      qualification: {
        type: 'STRING',
        description:
          'academic qualification. ONE of: HIGH_SCHOOL, DIPLOMA, BACHELOR, MASTER, PHD, OTHER',
        nullable: false,
      },
      specialization: {
        type: 'STRING',
        description:
          'job field. ONE of: ENGINEERING, INFORMATION_TECHNOLOGY, BUSINESS_ADMINISTRATION, ACCOUNTING_FINANCE, MARKETING_SALES, HEALTHCARE, EDUCATION, HUMAN_RESOURCES, OTHER',
        nullable: false,
      },
      category: {
        type: 'STRING',
        description: 'تصنيف الوظيفة مثل: هندسة البرمجيات، المحاسبة، التسويق',
        nullable: false,
      },
      description: { type: 'STRING', description: 'وصف مختصر للوظيفة في 2-3 جمل', nullable: false },
      experience: {
        type: 'STRING',
        description:
          'Required experience in Arabic. Use "غير محدد" if required experience is not mentioned.',
        nullable: false,
      },
      language: { type: 'STRING', description: 'لغة الإعلان: ar أو en', nullable: false },
      postedAt: {
        type: 'STRING',
        description: 'تاريخ نشر الإعلان بصيغة ISO 8601 — null لو مش موجود',
        nullable: true,
      },
      expiresAt: {
        type: 'STRING',
        description: 'تاريخ انتهاء الإعلان بصيغة ISO 8601 — null لو مش موجود',
        nullable: true,
      },
    },
    required: [
      'title',
      'companyName',
      'location',
      'qualification',
      'specialization',
      'category',
      'description',
      'experience',
      'language',
    ],
  },
};

export const DELAY_BETWEEN_SITES_MS = 2000;

export const MAX_CONCURRENT_REQUESTS = 5;

export const MAX_CONTENT_CHARS = 6000;

export const AI_REQUESTS_PER_MINUTE = 4;
