-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "JobLocation" ADD VALUE 'AL_KHARJ';
ALTER TYPE "JobLocation" ADD VALUE 'AL_DAWADIMI';
ALTER TYPE "JobLocation" ADD VALUE 'AL_MAJMAAH';
ALTER TYPE "JobLocation" ADD VALUE 'AL_QUWAYIYAH';
ALTER TYPE "JobLocation" ADD VALUE 'WADI_AD_DAWASIR';
ALTER TYPE "JobLocation" ADD VALUE 'AL_AFLAJ';
ALTER TYPE "JobLocation" ADD VALUE 'AL_ZULFI';
ALTER TYPE "JobLocation" ADD VALUE 'SHAQRA';
ALTER TYPE "JobLocation" ADD VALUE 'AFIF';
ALTER TYPE "JobLocation" ADD VALUE 'AS_SULAYYIL';
ALTER TYPE "JobLocation" ADD VALUE 'TAIF';
ALTER TYPE "JobLocation" ADD VALUE 'AL_QUNFUDHAH';
ALTER TYPE "JobLocation" ADD VALUE 'RABIGH';
ALTER TYPE "JobLocation" ADD VALUE 'AL_LAYTH';
ALTER TYPE "JobLocation" ADD VALUE 'KHULAIS';
ALTER TYPE "JobLocation" ADD VALUE 'YANBU';
ALTER TYPE "JobLocation" ADD VALUE 'AL_ULA';
ALTER TYPE "JobLocation" ADD VALUE 'MAHAD_AD_DAHAB';
ALTER TYPE "JobLocation" ADD VALUE 'BADR';
ALTER TYPE "JobLocation" ADD VALUE 'KHAYBAR';
ALTER TYPE "JobLocation" ADD VALUE 'BURAYDAH';
ALTER TYPE "JobLocation" ADD VALUE 'UNAIZAH';
ALTER TYPE "JobLocation" ADD VALUE 'AL_RASS';
ALTER TYPE "JobLocation" ADD VALUE 'AL_MITHNAB';
ALTER TYPE "JobLocation" ADD VALUE 'ASH_SHAMASIYAH';
ALTER TYPE "JobLocation" ADD VALUE 'AL_AHSA';
ALTER TYPE "JobLocation" ADD VALUE 'JUBAIL';
ALTER TYPE "JobLocation" ADD VALUE 'QATIF';
ALTER TYPE "JobLocation" ADD VALUE 'HAFR_AL_BATIN';
ALTER TYPE "JobLocation" ADD VALUE 'AL_KHAFJI';
ALTER TYPE "JobLocation" ADD VALUE 'ABHA';
ALTER TYPE "JobLocation" ADD VALUE 'KHAMIS_MUSHAIT';
ALTER TYPE "JobLocation" ADD VALUE 'BISHA';
ALTER TYPE "JobLocation" ADD VALUE 'AL_NAMAS';
ALTER TYPE "JobLocation" ADD VALUE 'MAHAYIL_ASIR';
ALTER TYPE "JobLocation" ADD VALUE 'DUBA';
ALTER TYPE "JobLocation" ADD VALUE 'TAYMA';
ALTER TYPE "JobLocation" ADD VALUE 'AL_WAJH';
ALTER TYPE "JobLocation" ADD VALUE 'UMLUJ';
ALTER TYPE "JobLocation" ADD VALUE 'HAIL';
ALTER TYPE "JobLocation" ADD VALUE 'BAQAA';
ALTER TYPE "JobLocation" ADD VALUE 'AL_GHAZALAH';
ALTER TYPE "JobLocation" ADD VALUE 'SAMIRA';
ALTER TYPE "JobLocation" ADD VALUE 'ARAR';
ALTER TYPE "JobLocation" ADD VALUE 'RAFHA';
ALTER TYPE "JobLocation" ADD VALUE 'TURAIF';
ALTER TYPE "JobLocation" ADD VALUE 'JIZAN';
ALTER TYPE "JobLocation" ADD VALUE 'SABYA';
ALTER TYPE "JobLocation" ADD VALUE 'ABU_ARISH';
ALTER TYPE "JobLocation" ADD VALUE 'SAMTAH';
ALTER TYPE "JobLocation" ADD VALUE 'BAISH';
ALTER TYPE "JobLocation" ADD VALUE 'NAJRAN';
ALTER TYPE "JobLocation" ADD VALUE 'SHARURAH';
ALTER TYPE "JobLocation" ADD VALUE 'BAHA';
ALTER TYPE "JobLocation" ADD VALUE 'BALJURASHI';
ALTER TYPE "JobLocation" ADD VALUE 'AL_MAKHWAH';
ALTER TYPE "JobLocation" ADD VALUE 'SAKAKA';
ALTER TYPE "JobLocation" ADD VALUE 'DUMAT_AL_JANDAL';
ALTER TYPE "JobLocation" ADD VALUE 'QURAYYAT';
